# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/chuy1/CS-281-Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/chuy1/CS-281-Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/chuy1/CS-281-Project/CMakeFiles /home/student/chuy1/CS-281-Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/chuy1/CS-281-Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mainClass

# Build rule for target.
mainClass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mainClass
.PHONY : mainClass

# fast build rule for target.
mainClass/fast:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/build
.PHONY : mainClass/fast

CdCommand.o: CdCommand.cpp.o
.PHONY : CdCommand.o

# target to build an object file
CdCommand.cpp.o:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/CdCommand.cpp.o
.PHONY : CdCommand.cpp.o

CdCommand.i: CdCommand.cpp.i
.PHONY : CdCommand.i

# target to preprocess a source file
CdCommand.cpp.i:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/CdCommand.cpp.i
.PHONY : CdCommand.cpp.i

CdCommand.s: CdCommand.cpp.s
.PHONY : CdCommand.s

# target to generate assembly for a file
CdCommand.cpp.s:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/CdCommand.cpp.s
.PHONY : CdCommand.cpp.s

CommandFactory.o: CommandFactory.cpp.o
.PHONY : CommandFactory.o

# target to build an object file
CommandFactory.cpp.o:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/CommandFactory.cpp.o
.PHONY : CommandFactory.cpp.o

CommandFactory.i: CommandFactory.cpp.i
.PHONY : CommandFactory.i

# target to preprocess a source file
CommandFactory.cpp.i:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/CommandFactory.cpp.i
.PHONY : CommandFactory.cpp.i

CommandFactory.s: CommandFactory.cpp.s
.PHONY : CommandFactory.s

# target to generate assembly for a file
CommandFactory.cpp.s:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/CommandFactory.cpp.s
.PHONY : CommandFactory.cpp.s

Exceptions.o: Exceptions.cpp.o
.PHONY : Exceptions.o

# target to build an object file
Exceptions.cpp.o:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Exceptions.cpp.o
.PHONY : Exceptions.cpp.o

Exceptions.i: Exceptions.cpp.i
.PHONY : Exceptions.i

# target to preprocess a source file
Exceptions.cpp.i:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Exceptions.cpp.i
.PHONY : Exceptions.cpp.i

Exceptions.s: Exceptions.cpp.s
.PHONY : Exceptions.s

# target to generate assembly for a file
Exceptions.cpp.s:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Exceptions.cpp.s
.PHONY : Exceptions.cpp.s

Parser.o: Parser.cpp.o
.PHONY : Parser.o

# target to build an object file
Parser.cpp.o:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Parser.cpp.o
.PHONY : Parser.cpp.o

Parser.i: Parser.cpp.i
.PHONY : Parser.i

# target to preprocess a source file
Parser.cpp.i:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Parser.cpp.i
.PHONY : Parser.cpp.i

Parser.s: Parser.cpp.s
.PHONY : Parser.s

# target to generate assembly for a file
Parser.cpp.s:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Parser.cpp.s
.PHONY : Parser.cpp.s

PipeCommand.o: PipeCommand.cpp.o
.PHONY : PipeCommand.o

# target to build an object file
PipeCommand.cpp.o:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/PipeCommand.cpp.o
.PHONY : PipeCommand.cpp.o

PipeCommand.i: PipeCommand.cpp.i
.PHONY : PipeCommand.i

# target to preprocess a source file
PipeCommand.cpp.i:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/PipeCommand.cpp.i
.PHONY : PipeCommand.cpp.i

PipeCommand.s: PipeCommand.cpp.s
.PHONY : PipeCommand.s

# target to generate assembly for a file
PipeCommand.cpp.s:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/PipeCommand.cpp.s
.PHONY : PipeCommand.cpp.s

Process.o: Process.cpp.o
.PHONY : Process.o

# target to build an object file
Process.cpp.o:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Process.cpp.o
.PHONY : Process.cpp.o

Process.i: Process.cpp.i
.PHONY : Process.i

# target to preprocess a source file
Process.cpp.i:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Process.cpp.i
.PHONY : Process.cpp.i

Process.s: Process.cpp.s
.PHONY : Process.s

# target to generate assembly for a file
Process.cpp.s:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Process.cpp.s
.PHONY : Process.cpp.s

Shell.o: Shell.cpp.o
.PHONY : Shell.o

# target to build an object file
Shell.cpp.o:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Shell.cpp.o
.PHONY : Shell.cpp.o

Shell.i: Shell.cpp.i
.PHONY : Shell.i

# target to preprocess a source file
Shell.cpp.i:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Shell.cpp.i
.PHONY : Shell.cpp.i

Shell.s: Shell.cpp.s
.PHONY : Shell.s

# target to generate assembly for a file
Shell.cpp.s:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/Shell.cpp.s
.PHONY : Shell.cpp.s

StartProcessCommand.o: StartProcessCommand.cpp.o
.PHONY : StartProcessCommand.o

# target to build an object file
StartProcessCommand.cpp.o:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/StartProcessCommand.cpp.o
.PHONY : StartProcessCommand.cpp.o

StartProcessCommand.i: StartProcessCommand.cpp.i
.PHONY : StartProcessCommand.i

# target to preprocess a source file
StartProcessCommand.cpp.i:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/StartProcessCommand.cpp.i
.PHONY : StartProcessCommand.cpp.i

StartProcessCommand.s: StartProcessCommand.cpp.s
.PHONY : StartProcessCommand.s

# target to generate assembly for a file
StartProcessCommand.cpp.s:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/StartProcessCommand.cpp.s
.PHONY : StartProcessCommand.cpp.s

mainClass.o: mainClass.cpp.o
.PHONY : mainClass.o

# target to build an object file
mainClass.cpp.o:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/mainClass.cpp.o
.PHONY : mainClass.cpp.o

mainClass.i: mainClass.cpp.i
.PHONY : mainClass.i

# target to preprocess a source file
mainClass.cpp.i:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/mainClass.cpp.i
.PHONY : mainClass.cpp.i

mainClass.s: mainClass.cpp.s
.PHONY : mainClass.s

# target to generate assembly for a file
mainClass.cpp.s:
	$(MAKE) -f CMakeFiles/mainClass.dir/build.make CMakeFiles/mainClass.dir/mainClass.cpp.s
.PHONY : mainClass.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mainClass"
	@echo "... rebuild_cache"
	@echo "... CdCommand.o"
	@echo "... CdCommand.i"
	@echo "... CdCommand.s"
	@echo "... CommandFactory.o"
	@echo "... CommandFactory.i"
	@echo "... CommandFactory.s"
	@echo "... Exceptions.o"
	@echo "... Exceptions.i"
	@echo "... Exceptions.s"
	@echo "... Parser.o"
	@echo "... Parser.i"
	@echo "... Parser.s"
	@echo "... PipeCommand.o"
	@echo "... PipeCommand.i"
	@echo "... PipeCommand.s"
	@echo "... Process.o"
	@echo "... Process.i"
	@echo "... Process.s"
	@echo "... Shell.o"
	@echo "... Shell.i"
	@echo "... Shell.s"
	@echo "... StartProcessCommand.o"
	@echo "... StartProcessCommand.i"
	@echo "... StartProcessCommand.s"
	@echo "... mainClass.o"
	@echo "... mainClass.i"
	@echo "... mainClass.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

